
project_id = "dlequbzzlavikbxgzlkc"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[functions]
enabled = true

[functions.n8n-webhook]
verify_jwt = false
