// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlequbzzlavikbxgzlkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZXF1Ynp6bGF2aWtieGd6bGtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTg4MjQsImV4cCI6MjA2MzE5NDgyNH0.whY2CjAAgcIgqGgcRxuDEOSEQy1eSmREUiHD6OTLAnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);